spring.application.name=trade-service
server.port=8600

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.circuitbreaker.instances.cryptoExchange.sliding-window-size=5
resilience4j.circuitbreaker.instances.cryptoExchange.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.cryptoExchange.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cryptoExchange.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.cryptoExchange.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.cryptoExchange.ignore-exceptions=feign.FeignException$FeignClientException

resilience4j.circuitbreaker.instances.currencyConversion.sliding-window-size=5
resilience4j.circuitbreaker.instances.currencyConversion.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.currencyConversion.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.currencyConversion.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.currencyConversion.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.currencyConversion.ignore-exceptions=feign.FeignException$FeignClientException

resilience4j.timelimiter.instances.cryptoExchange.timeout-duration=5s
resilience4j.timelimiter.instances.currencyConversion.timeout-duration=10s
