spring.application.name=crypto-exchange-service
server.port=8400

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

resilience4j.retry.instances.coingecko.max-attempts=8
resilience4j.retry.instances.coingecko.wait-duration=2s
